global:
  imagePullSecret:
    name: container-registry
  domain: null
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    db:
      fromSecret: cpapp-db
  image:
    repository: <your-container-registry>/cpapp-srv
    tag: latest
  resources:
    limits:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
    requests:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: cpapp
    role-collections:
      - description: Manage Risks
        name: RiskManager
        role-template-references:
          - '$XSAPPNAME.RiskManager'
      - description: View Risks
        name: RiskViewer
        role-template-references:
          - '$XSAPPNAME.RiskViewer'
  config: xs-security.json
hana_deployer:
  image:
    repository: <your-container-registry>/cpapp-hana-deployer
    tag: latest
  bindings:
    hana:
      fromSecret: cpapp-db
destinations:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
html5_apps_deployer:
  cloudService: cpapp.service
  backendDestinations:
    cpapp-srv:
      service: srv
  image:
    repository: <your-container-registry>/cpapp-html5-deployer
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destinations
    html5_apps_repo:
      serviceInstanceName: html5-apps-repo-host
html5_apps_repo_host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
